version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT port
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped